rasterizer_cpp:
	g++ -o rasterizer hw2_math_ops.cpp hw2_file_ops.cpp rasterizer.cpp 

rasterizer_c:
	gcc -o rasterizer hw2_math_ops.c hw2_file_ops.c rasterizer.c -lm

clean:
	rm -rf *.ppm *.png ./rasterizer
